# tools\env.py
from pathlib import Path
import os

# ── Load app identity from .env.default ───────────────────────────────────
# Single source of truth for APP_NAME, APP_AUTHOR, ENTRY_POINT, PYTHON_ZIP_NAME.
# All other scripts derive from this file — never hardcode these values.

_default_env = Path(__file__).parent / ".env.default"

if not _default_env.exists():
    raise FileNotFoundError(
        f".env.default not found at {_default_env}\n"
        f"Ensure tools\\.env.default is committed to the repo."
    )

_config: dict[str, str] = {}
for line in _default_env.read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if line and not line.startswith("#") and "=" in line:
        key, _, value = line.partition("=")
        _config[key.strip()] = value.strip()

APP_NAME        = _config["APP_NAME"]
APP_AUTHOR      = _config["APP_AUTHOR"]
ENTRY_POINT     = _config["ENTRY_POINT"]
PYTHON_ZIP_NAME = _config["PYTHON_ZIP_NAME"]

# ── Python minimum version ─────────────────────────────────────────────────
PYTHON_MIN      = (3, 12)                     # ← restored

# ── Project source root (on shared drive) ─────────────────────────────────
# Always resolves correctly regardless of drive letter or UNC path.
PROJECT_DIR     = Path(__file__).resolve().parent.parent
PYTHON_ZIP      = PROJECT_DIR / PYTHON_ZIP_NAME

# ── Boot interpreter (committed to repo — lives on shared drive) ──────────
BOOT_DIR        = PROJECT_DIR / "tools" / "boot"
BOOT_PYTHON     = BOOT_DIR / "python.exe"

# ── User-local base ───────────────────────────────────────────────────────
_local_app_dir  = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))

# ── Shared across all apps by this organisation ───────────────────────────
_org_root       = _local_app_dir / APP_AUTHOR
PORTABLE_DIR    = _org_root / "python"        # shared by all org apps

# ── Per-application paths ─────────────────────────────────────────────────
_app_root       = _local_app_dir / APP_AUTHOR / APP_NAME
VENV_DIR        = _app_root / ".venv"
LOG_DIR         = _app_root / "logs"
DATA_DIR        = _app_root / "data"
CONFIG_DIR      = _app_root / "config"

# ── Entry path ────────────────────────────────────────────────────────────
ENTRY_PATH      = PROJECT_DIR / ENTRY_POINT

def write_env_file() -> None:
    r"""
    Write resolved paths to a user-local .env file in AppData.
    Safe for multi-user shared drive deployments.
    APP_NAME, APP_AUTHOR, ENTRY_POINT and PYTHON_ZIP_NAME are
    sourced from tools\.env.default.
    """                                        # ← raw string fixes invalid escape
    env_file = _app_root / ".env"
    _app_root.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by tools/env.py — do not edit manually",
        f"PROJECT_DIR={PROJECT_DIR}",
        f"PORTABLE_DIR={PORTABLE_DIR}",
        f"VENV_DIR={VENV_DIR}",
        f"LOG_DIR={LOG_DIR}",
        f"DATA_DIR={DATA_DIR}",
        f"CONFIG_DIR={CONFIG_DIR}",
        f"BOOT_DIR={BOOT_DIR}",
        f"ENTRY_POINT={ENTRY_POINT}",
        f"APP_NAME={APP_NAME}",
        f"APP_AUTHOR={APP_AUTHOR}",
        f"PYTHON_ZIP_NAME={PYTHON_ZIP_NAME}",
    ]
    env_file.write_text("\n".join(lines), encoding="utf-8")
